<template>
  <div class="table">
    <div class="table-head">
      <div class="table-col">
        <TableColHeader  :sortable="true" @sortBy="sortType" text="Names" class="text-left"></TableColHeader>
      </div>
      <div class="table-col">
        <TableColHeader  :sortable="false"  text="Size" class="text-center"></TableColHeader>
      </div>
      <div class="table-col">
        <TableColHeader  :sortable="false" text="Type" class="text-center"></TableColHeader>
      </div>
      <div class="table-col">
        <TableColHeader  :sortable="false" text="Download" class="text-center"></TableColHeader>
      </div>
    </div>
    <div class="table-body">
      <div class="table-row" v-if="loading">
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>                        
      </div>
      <div class="table-row"  v-for="download in downloads"  v-if="!loading">
        
        <div class="table-col text-left">
          <span>{{ download.fields["display-name"] }}</span>
        </div>
        <div class="table-col">
          
          <!-- <FileSize v-if="download.fields.filesize" v-bind:size="download.fields.filesize" v-bind:url="download.fields.file"></Filesize> -->
          {{download.fields.filesize}}
        </div>
        <div class="table-col">
          <FileType v-bind:url="download.fields['computed-download-url']"></FileType>
        </div>
        <div class="table-col">
          <Button v-bind:href="download.fields['computed-download-url']" size="small" type="secondary"></Button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>

import Button from './atoms/Button.vue'
import TableColHeader from './atoms/TableColHeader.vue'
import FileSize from './atoms/FileSize.vue'
import FileType from './atoms/FileType.vue'
import slug from './atoms/slug.vue'

export default {

  name: 'DownloadsTable',
  data() {
    return {
      columns: ["display-name", "type", "filesize", "file.url"],
    };
  },
  props: {
    downloads: Object,
    loading: Boolean
  },
  components: {
        Button,
        TableColHeader,
        FileSize,
        FileType,
        slug
  },
  emits: ['sortBy'],
  methods: {
    sortType(event) {
      this.$emit('sortBy',event)
      // console.log(event)
    },
  }

};
</script>

<style lang="css">
.table-col, td.table-col {
  padding:10px;
  width:100%;
  border-right:1px solid transparent;
}

.table-row, .table-head {
  display:flex;
}

.table-head {
  font-weight:bold;
  background:#f9f9f9;
}

.text-left {
  text-align: left;
}

.loadingSpan {
  display:block;
  padding:0.75em;
  background:#f3f3f3;
  -webkit-animation: blink-1 0.5s ease-in-out infinite both;
          animation: blink-1 0.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-4-8 15:11:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation blink-1
 * ----------------------------------------
 */
@-webkit-keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}
@keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}

</style>
